version: "3.1"

services:
  zookeeper:
    image: zookeeper
    container_name: ondc-zookeeper
    restart: always
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    container_name: ondc-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

#  nimbus:
#     image: storm
#     container_name: ondc-storm-nimbus
#     command: storm nimbus
#     depends_on:
#       - zookeeper
#     links:
#       - zookeeper
#     restart: always
#     ports:
#       - 6627:6627
#
#  supervisor:
#     image: storm
#     container_name: ondc-storm-supervisor
#     command: storm supervisor
#     depends_on:
#       - nimbus
#       - zookeeper
#     links:
#       - nimbus
#       - zookeeper
#     restart: always
#
#  ui:
#     image: storm
#     container_name: ondc-storm-ui
#     command: storm ui
#     depends_on:
#       - nimbus
#     links:
#       - nimbus
#     restart: always
#     ports:
#       - 8080:8080

  solr:
    image: solr
    container_name: ondc-solr
    ports:
      - 8983:8983
    environment:
      - SOLR_HOME=/opt/solr/server/solr/configsets/
    volumes:
      - ./solr-config:/opt/solr/server/solr/configsets/
